"""Added Register

Revision ID: e87727ca0d50
Revises: cca121e6396b
Create Date: 2018-10-18 09:01:41.611063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87727ca0d50'
down_revision = 'cca121e6396b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('team_no', sa.String(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Register')
    # ### end Alembic commands ###
